INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Nacional do Brasil', 'Av. Rio Branco, 219, 100', 'Rio de Janeiro', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Mário de Andrade', 'R. da Consolação, 94, 101', 'São Paulo', 'municipal');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Pública do Estado da Bahia', 'R. General Labatut, 27, 102', 'Salvador', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Central da UFC', 'Av. da Universidade, 2853, 103', 'Fortaleza', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Pública de Minas Gerais', 'Praça da Liberdade, 21, 104', 'Belo Horizonte', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Central da UnB', 'Campus Universitário Darcy Ribeiro, 105', 'Brasília', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Pública do Paraná', 'R. Cândido Lopes, 133, 106', 'Curitiba', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Central da UFPE', 'Av. Prof. Moraes Rego, 1235, 107', 'Recife', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Pública do Estado do Rio Grande do Sul', 'R. Riachuelo, 1190, 108', 'Porto Alegre', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Municipal de Manaus', 'R. Barroso, 57, 109', 'Manaus', 'municipal');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Nacional do Brasil - Anexo 2', 'Av. Rio Branco, 219, 110', 'Rio de Janeiro', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Mário de Andrade - Anexo 2', 'R. da Consolação, 94, 111', 'São Paulo', 'municipal');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Pública do Estado da Bahia - Anexo 2', 'R. General Labatut, 27, 112', 'Salvador', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Central da UFC - Anexo 2', 'Av. da Universidade, 2853, 113', 'Fortaleza', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Pública de Minas Gerais - Anexo 2', 'Praça da Liberdade, 21, 114', 'Belo Horizonte', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Central da UnB - Anexo 2', 'Campus Universitário Darcy Ribeiro, 115', 'Brasília', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Pública do Paraná - Anexo 2', 'R. Cândido Lopes, 133, 116', 'Curitiba', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Central da UFPE - Anexo 2', 'Av. Prof. Moraes Rego, 1235, 117', 'Recife', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Pública do Estado do Rio Grande do Sul - Anexo 2', 'R. Riachuelo, 1190, 118', 'Porto Alegre', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Municipal de Manaus - Anexo 2', 'R. Barroso, 57, 119', 'Manaus', 'municipal');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Nacional do Brasil - Anexo 3', 'Av. Rio Branco, 219, 120', 'Rio de Janeiro', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Mário de Andrade - Anexo 3', 'R. da Consolação, 94, 121', 'São Paulo', 'municipal');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Pública do Estado da Bahia - Anexo 3', 'R. General Labatut, 27, 122', 'Salvador', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Central da UFC - Anexo 3', 'Av. da Universidade, 2853, 123', 'Fortaleza', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Pública de Minas Gerais - Anexo 3', 'Praça da Liberdade, 21, 124', 'Belo Horizonte', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Central da UnB - Anexo 3', 'Campus Universitário Darcy Ribeiro, 125', 'Brasília', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Pública do Paraná - Anexo 3', 'R. Cândido Lopes, 133, 126', 'Curitiba', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Central da UFPE - Anexo 3', 'Av. Prof. Moraes Rego, 1235, 127', 'Recife', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Pública do Estado do Rio Grande do Sul - Anexo 3', 'R. Riachuelo, 1190, 128', 'Porto Alegre', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Municipal de Manaus - Anexo 3', 'R. Barroso, 57, 129', 'Manaus', 'municipal');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Nacional do Brasil - Anexo 4', 'Av. Rio Branco, 219, 130', 'Rio de Janeiro', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Mário de Andrade - Anexo 4', 'R. da Consolação, 94, 131', 'São Paulo', 'municipal');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Pública do Estado da Bahia - Anexo 4', 'R. General Labatut, 27, 132', 'Salvador', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Central da UFC - Anexo 4', 'Av. da Universidade, 2853, 133', 'Fortaleza', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Pública de Minas Gerais - Anexo 4', 'Praça da Liberdade, 21, 134', 'Belo Horizonte', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Central da UnB - Anexo 4', 'Campus Universitário Darcy Ribeiro, 135', 'Brasília', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Pública do Paraná - Anexo 4', 'R. Cândido Lopes, 133, 136', 'Curitiba', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Central da UFPE - Anexo 4', 'Av. Prof. Moraes Rego, 1235, 137', 'Recife', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Pública do Estado do Rio Grande do Sul - Anexo 4', 'R. Riachuelo, 1190, 138', 'Porto Alegre', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Municipal de Manaus - Anexo 4', 'R. Barroso, 57, 139', 'Manaus', 'municipal');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Nacional do Brasil - Anexo 5', 'Av. Rio Branco, 219, 140', 'Rio de Janeiro', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Mário de Andrade - Anexo 5', 'R. da Consolação, 94, 141', 'São Paulo', 'municipal');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Pública do Estado da Bahia - Anexo 5', 'R. General Labatut, 27, 142', 'Salvador', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Central da UFC - Anexo 5', 'Av. da Universidade, 2853, 143', 'Fortaleza', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Pública de Minas Gerais - Anexo 5', 'Praça da Liberdade, 21, 144', 'Belo Horizonte', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Central da UnB - Anexo 5', 'Campus Universitário Darcy Ribeiro, 145', 'Brasília', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Pública do Paraná - Anexo 5', 'R. Cândido Lopes, 133, 146', 'Curitiba', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Central da UFPE - Anexo 5', 'Av. Prof. Moraes Rego, 1235, 147', 'Recife', 'estadual');
INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Pública do Estado do Rio Grande do Sul - Anexo 5', 'R. Riachuelo, 1190, 148', 'Porto Alegre', 'estadual');

INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Municipal de Manaus - Anexo 5', 'R. Barroso, 57, 149', 'Manaus', 'municipal');

INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Municipal de Manaus - Anexo 6', 'R. Barroso, 57, 149', 'Manaus', 'municipal');

INSERT INTO Biblioteca (nome, endereco, cidade, categoria) VALUES ('Biblioteca Municipal de Guaraus', 'R. das Lagrimas, 57, 149', 'Guaraus', 'municipal');